[package]
name = "glyph-atlas"
version = "0.1.0"
authors = ["Jason Han <jjhan@alum.vassar.edu>"]
license = "MIT"
description = "A fast, cross-platform, OpenGL text editor experiment"
readme = "README.md"
homepage = "https://github.com/jason5122/glyph-atlas"
edition = "2021"
rust-version = "1.65.0"

[dependencies]
ahash = { version = "0.8.3", features = ["no-rng"] }
bitflags = "2.2.1"
crossfont = { version = "0.5.0", features = ["force_system_fontconfig"] }
glutin = { version = "0.30.4" }
home = "0.5.5"
libc = "0.2"
log = { version = "0.4", features = ["std"] }
once_cell = "1.12"
raw-window-handle = "0.5.0"
unicode-width = "0.1"
winit = { version = "0.29.0-beta.0" }
crop = { version = "0.3.0", features = ["graphemes"] }
unicode-segmentation = "1.10.1"

[build-dependencies]
gl_generator = "0.14.0"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24.0"
objc = "0.2.2"

[profile.release]
lto = "thin"
opt-level = 3
incremental = false
